apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-stack
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-3" # THIRD to Deploy
spec:
  project: default
  source:
    repoURL: https://github.com/srjbis/cloud-deploy.git
    path: helm/istio-stack
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true