apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring-stack
  namespace: monitoring
spec:
  project: default
  source:
    repoURL: https://github.com/srjbis/cloud-deploy.git
    path: monitoring-stack
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring