apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: frontend-route
  namespace: {{ .Values.namespace }}
spec:
  hosts:
    - {{ .Values.ingress.host | quote }}
  gateways:
    - app-gateway
  http:
    - route:
        - destination:
            host: frontend
            port:
              number: 80