namespace: application

redis:
  password: Password

api:
  replicas: 3
  image: hashicorp/http-echo
  cpuRequest: "100m"
  memoryRequest: "128Mi"
  cpuLimit: "300m"
  memoryLimit: "256Mi"

frontend:
  image: nginx:stable

ingress:
  host: srjbis.online

hpa:
  minReplicas: 3
  maxReplicas: 10
  cpuUtilization: 50