apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluentbit
  namespace: {{ .Values.namespace }}
spec:
  selector:
    matchLabels:
      app: fluentbit
  template:
    metadata:
      labels:
        app: fluentbit
    spec:
      containers:
      - name: fluentbit
        image: {{ .Values.fluentbit.image }}
        volumeMounts:
        - name: varlog
          mountPath: /var/log
      volumes:
      - name: varlog
        hostPath:
          path: /var/log