apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jaeger
  template:
    metadata:
      labels:
        app: jaeger
    spec:
      containers:
      - name: jaeger
        image: {{ .Values.jaeger.image }}
        ports:
        - containerPort: {{ .Values.jaeger.port }}